### ISSUE TITLE
gradcheck of the neural

### ISSUE THREAD

**Issue by luxuriance19** [rohitapte/cs224N#1]
I implement the q2_neural, but it can't pass the gradcheck function, I don't know the reason.
the error message is 
```
Traceback (most recent call last):
  File "q2_neural.py", line 102, in <module>
    sanity_check()
  File "q2_neural.py", line 85, in sanity_check
    forward_backward_prop(data, labels, params, dimensions), params)
  File "/home/lily/Downloads/model_global/self_interest/CS224N/assignment1/q2_gradcheck.py", line 43, in gradcheck_naive
    fx_add_h = f(x_+h)[0]
  File "q2_neural.py", line 85, in <lambda>
    forward_backward_prop(data, labels, params, dimensions), params)
  File "q2_neural.py", line 33, in forward_backward_prop
    W1 = np.reshape(params[ofs:ofs+ Dx * H], (Dx, H))
IndexError: invalid index to scalar variable.

```
Did you encounter this problem, Thansk

**Comment by rohitapte** [comment]
are you running it in python 2.7 or 3.X?

when I did this course they were still using python 2.7. otherwise I need to dig deeper

**Comment by luxuriance19** [comment]
> are you running it in python 2.7 or 3.X?
> 
> when I did this course they were still using python 2.7. I need to dig deeper

I used it in python 3.6, Thanks
